---
kafka_port: 9092

kafka_num_network_threads: '{{ansible_processor_vcpus}}'
kafka_num_io_threads: '{{ansible_processor_vcpus}}'
kafka_num_partitions: 1

kafka_socket_send_buffer_bytes: 1048576
kafka_socket_receive_buffer_bytes: 1048576
kafka_socket_request_max_bytes: 104857600

kafka_log_flush_interval_messages: 10000
kafka_log_flush_interval_ms: 1000
kafka_log_retention_bytes: 104857600  #100 M
kafka_log_retention_hours: 24
kafka_log_segment_bytes: '{{kafka_log_retention_bytes}}'

zookeeper_connection_timeout_ms: 6000
