---

- name: Install pip
  sudo: yes
  shell: easy_install pip creates=/usr/local/bin/pip

- name: uninstall old concord-py and old concord cli
  sudo: yes
  pip:
    state=absent
    name='{{item}}'
  ignore_errors: yes
  with_items:
    - 'concord-py'
    - 'concord'

- name: install concord py and concord cli
  sudo: yes
  pip:
    state=present
    name='{{item.name}}'
    version='{{item.version}}'
  with_items:
    - {name: 'concord-py', version: '{{concord_py_version}}'}
    - {name: 'concord', version: '{{concord_cli_version}}'}

- name: install virtualenv
  sudo: yes
  pip: state=present name=virtualenv
