---
- name: Set up Concord dependencies
  hosts: all
  tasks:
    - name: Install apt tools
      sudo: yes
      apt: state=present name={{item}}
      with_items:
        - apt-transport-https
        - software-properties-common

    # - name: Register mesos apt keys
    #   sudo: yes
    #   apt_key: state=present id=E56151BF keyserver=keyserver.ubuntu.com

    - name: Register apt repos
      sudo: yes
      apt_repository: repo='{{item}}' update_cache=yes state=present
      with_items:
        - ppa:ubuntu-toolchain-r/test
        - ppa:webupd8team/java
          # - deb http://repos.mesosphere.io/ubuntu trusty main

    - name: Auto accept oracle jdk license
      sudo: yes
      shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

    - name: Install apt packages
      sudo: yes
      apt: state=present name={{item}} update_cache=yes
      with_items:
        - git
        - curl
        - bzip2
        - libntl0
        - libmpfr4
        - libssl1.0.0
        - libgflags2
        - libboost-thread1.55.0
        - libboost-regex1.55.0
        - libboost-program-options1.55.0
        - libboost-system1.55.0
        - libboost-filesystem1.55.0
        - libboost-date-time1.55.0
        - libboost-iostreams1.55.0
        - libevent-2.0-5
        - libunwind8
        - libdouble-conversion1
        - liblz4-1
        - liblzma5
        - libsnappy1
        - libjemalloc1
        - libgoogle-glog0
        - zlib1g
        - libbz2-1.0
        - libarchive13
        - libcurl3-nss
        - libsvn1
        - libsasl2-2
        - libapr1
        - libasan2
        - lttng-tools
        - liblttng-ust0
        - libstdc++6=5.1.0-0ubuntu11~14.04.1
          #- mesos=0.23.0-1.0.ubuntu1404
        - zookeeperd
        - python-setuptools
        - oracle-java8-installer
        - ca-certificates
        - ruby2.0
        - ruby2.0-dev

    - name: Install pip
      sudo: yes
      shell: easy_install pip creates=/usr/local/bin/pip

    - name: Install custom libs
      sudo: yes
      shell: curl -L {{item.url}} | tar zxf -
             chdir=/ creates={{item.creates}}
      with_items:
        - url: https://storage.googleapis.com/concord-libs/cityhash-1.1.1-lib.tar.gz
          creates: /usr/local/lib/libcityhash.so
        - url: https://storage.googleapis.com/concord-libs/folly-0.31.0-lib.tar.gz
          creates: /usr/local/lib/libfolly.so
        - url: https://storage.googleapis.com/concord-libs/rocksdb-3.11.2-lib.tar.gz
          creates: /usr/local/lib/librocksdb.so
        - url: https://storage.googleapis.com/concord-libs/thrift-0.9.2-lib.tar.gz
          creates: /usr/local/lib/libthrift.so
        - url: https://storage.googleapis.com/concord-libs/mesos-0.23.0-lib.tar.gz
          creates: /usr/local/lib/libmesos.so
        - url: https://storage.googleapis.com/concord-libs/mesos-0.23.0-runtime.tar.gz
          creates: /usr/local/sbin/mesos-master

    # - name: Install custom debs
    #   sudo: yes
    #   shell: cd $(mktemp -d) && wget {{item.url}} && dpkg -i {{item.file}}
    #          creates={{item.creates}}
    #   with_items:
    #     - url: https://storage.googleapis.com/concord-debs/cityhash-1.1.1-dev.deb
    #       file: cityhash-1.1.1-dev.deb
    #       creates: /usr/lib/libcityhash.so
    #     - url: https://storage.googleapis.com/concord-debs/folly-0.31.0-dev.deb
    #       file: folly-0.31.0-dev.deb
    #       creates: /usr/lib/libfolly.so
    #     - url: https://storage.googleapis.com/concord-debs/rocksdb-3.11.2-dev.deb
    #       file: rocksdb-3.11.2-dev.deb
    #       creates: /usr/lib/librocksdb.so
    #     - url: https://storage.googleapis.com/concord-debs/thrift-0.9.2-dev.deb
    #       file: thrift-0.9.2-dev.deb
    #       creates: /usr/lib/libthrift.so

    - name: Create install path for concord
      sudo: yes
      file: state=directory path=/usr/local/share/concord recurse=yes

    - name: Install init script for concord
      sudo: yes
      copy: src=files/concord.conf dest=/etc/init/concord.conf
      register: init_script

    # - name: Install mesos configs
    #   sudo: yes
    #   copy: src=files/mesos_hostname dest=/etc/mesos-{{item}}/hostname
    #   with_items:
    #     - master
    #     - slave

    - name: Restart concord
      sudo: yes
      service: name=concord state=restarted
      when: init_script.changed

